[versions]
compileSdk = "34"
minSdk = "26"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"
testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
proguardFiles = "proguard-rules.pro"
getDefaultProguardFile = "proguard-android-optimize.txt"    